---
title: "Phyloseq PreProcessing"
author: "Erica Sawyer"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r Load Libraries, echo=FALSE}
library(devtools)
BiocManager::install("phyloseq")

library(phyloseq)

# may need to load tidy verse
```

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.path = "/local/workdir/es986/git_repos/SalinityGradient_16S/figures/02_PreProcessing/")
```

#Goals

Here we will process the data into a phyloseq object.

-ASV Table
-Taxonomy Table
-Track Reads (metadata)

Then, we will remove the following:

1. Remove chloroplasts
2. Remove mitochondira
3. Remove samples without 'enought' reads

Finally write data file of phyloseq object



# Load Data
## ASV Table
```{r Load ASV Table}
# First load ASV Table
load("data/01_DADA2/ASV_counts.RData")

# Inspect asv_tab
head(asv_tab)[,1:5]

# Fix names 
sample_names <- colnames(asv_tab)
samples_fixed <- sapply(strsplit(basename(sample_names), "_"), `[`,1) 
head(samples_fixed)

# re-write the ASV count file to fix names
colnames(asv_tab) <- samples_fixed
str(asv_tab)

```

## Taxonomy Table
```{r Load Taxonomy Table}
tax_df <- read.table("data/01_DADA2/ASV_taxonomy.tsv", sep = "\t", skip=1)
head(tax_df)

# fix column names
colnames(tax_df) <- c("ASV", "Kingdom", "Phylum", "Class", "Order", "Family", "Genius", "Species", "ASV", "ASVseq")

head(tax_df)
# Taxonomy table matrix

tax_mat <- 
  tax_df %>%
  tibble::column_to_rownames(., var = "asv_names") %>%
  as.matrix()

```

## Track Reads Table
```{r Load Track Reads Table}


```

# Handoff to Phyloseq
```{r}

```
