---
title: "Biodiversity Analysis"
author: "Erica Sawyer"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = "figures/04_Biodiversity/")
```


# Setting the Environment
```{r set env}
# Set Seed
set.seed(238428)

```

# Load Libraries
```{r lib}
pacman::p_load(tidyverse, devtools, patchwork, iNEXT, phyloseq, install=FALSE)

```
# Load in Data
```{r data}
load("data/02_PreProcessing/raw_preprocessed_physeq.RData")
raw_preprocessed_physeq

#intuition check
min(sample_sums(raw_preprocessed_physeq))

#Setting colors for stations
station_colors <- c(
  "Shipping Channel" = "dodgerblue4",
  "Aransas Bay" = "dodgerblue2",
  "Copano West" = "#D9CC3C",
  "Copano East" = "#A0E0BA",
  "Mesquite Bay" = "#00ADA7")


```


# Goals
1.

# Diversity Calculations with iNEXT
```{r calc div}
iNEXT_input_df <- 
  raw_preprocessed_physeq %>%
  otu_table() %>%
  data.frame()

# check # somehow you are missing one ASV
dim(iNEXT_input_df)

# run iNEXT to calculate hill numbers
# Note species in rows, samples in columns
# remember to set seed

#iNEXT_data <-
  #iNEXT(iNEXT_input_df, q = c(0,1,2), datatype = "abundance") # q0= richenss, q1=shannon, q2=simpson

# Save the file
#save(iNEXT_data, file = "data/04_Biodiversity/iNEXT_data.RData")

```

# Evaluate Diversity
```{r eval div}
load("data/04_Biodiversity/iNEXT_data.RData")
str(iNEXT_data)
typeof(iNEXT_data)



```

# plot diversity
```{r plot rarefaction}
# Prepare colors
color_df <- 
  iNEXT_input_df %>%
  colnames() %>%
  data.frame()

head(color_df)
#Rename column
colnames(color_df)[1] <- "names"


```